symfonycasts_reset_password:
    request_password_repository: App\Repository\ResetPasswordRequestRepository
    lifetime: 3600
    throttle_limit: 0

#symfonycasts_reset_password:
#    mail:
#        enabled: true
#        message_bus: false
#    # Replace symfonycasts.reset_password.fake_request_repository with the full
#    # namespace of the password reset request repository after it has been created.
#    # i.e. App\Repository\ResetPasswordRequestRepository
#    request_password_repository: symfonycasts.reset_password.fake_request_repository
